// Script: Script1.script
// Autor: Gabriel Maia, Felipe Zarattini, Felipe Holanda
// Data: 13/abr/2014
// Propósito: Testar o módulo Pilha de Cartas

==Inserir Carta
=adicionar "9" 'c' 1 1 3

==Criar Pilha
=criarpilha 0

==Retirar Carta
=remover 2

==Inserir Carta
=adicionar "9" 'c' 1 1 0

==Inserir Carta
=adicionar "9" 'c' 1 1 0

==Retirar Carta
=remover 0

==Retirar Carta
=remover 0

==Destruir Pilha
=destruirpilha 0
